### ISSUE TITLE
Missing data in a time-varying covariate

### ISSUE THREAD

**Issue by JacopoCerri** [jlaake/marked#13]
****
Hi you all,

I am fitting a Cormack-Jolly-Seber model with marked, to model the survival of Alpine marmots over a 10-years timespan. Individuals were trapped at the beginning and at the end of the summer season and we would like to estimate their apparent survival in function of some covariates.
In the dataset there is a time-varying covariate describing the age class of captured individuals, which were classified as "young" (1 or 2 years old) or as "adults" (3 or more years of age). From the vignette, including a time-varying covariate seems to be easy (though the one in the example with dippersis not measured at the individual level, [https://cran.r-project.org/web/packages/marked/vignettes/markedVignette.html]), however the model tells me that there are some missing data in this variable.
Of course there are missing values, as there are _n_ columms for this covariate, one for each trapping session, and individuals do not have a value for this covariate until the column of the session when they were trapped. But how can I fix this issue? I figured out that there might be two solutions:

- replenishing missing data with one of the two values of the variable, considered that these will be ignored by the model as it will consider only the capture history. But will it really ignore them in the estimation of p(capture)?

- writing down missing data as zeroes and then representing the other two levels in the numeric format, as 1 or 2. But at that point the variable will be treated as a number, which is not the case.

How should I proceed?

Kind regards,

Jacopo Cerri

**Comment by CarvalhoRafaelRamos** [comment]
Hi, Jacopo!

Did you find the answer for this issue? 
I was wondering if the missing values could not be represented with "NA".

Kind regards,
Rafael Carvalho

**Comment by jlaake** [comment]
My sincere apologies for not replying. I have not been getting emails about issues so I was unaware of this post. Technically your post is not an issue with the software but is a problem on how to use the software. There is a forum for marked users. It is under http://www.phidot.org/forum/index.php  It doesn't get a lot of usage but I do monitor it and answer questions.  This post is rather old so I'm presuming you have worked out a solution or gave up. 

For a CJS type model, data prior to the first capture are not used in the likelihood, so you can use any numeric value for time varying covariates up to and including the first capture. p is only modelled for subsequent captures after the first. So you could have used 0 for all of those prior values. NA will not work.  Age doesn't really need to be handled as a time varying covariate because marked has the capability to specify an initial age at first capture and it will them age the animal through time in the design data which nullifies the need for time varying covariate.  But to do so you need to know the animals age and with your grouping of 1 to 2 as young that would suggest that you only know that the animal is young but you don't know its actual age since birth. In any capture-recapture model if you only know age grouping and not age, you can assign a mid-point as the initial age and accept the non-measured uncertainty that creates or you can treat as a multistate model where the aging is a transition between age groupings.
